### ISSUE TITLE
Current day's data missing in states_daily.json

### ISSUE THREAD

**Issue by Sdaas** [covid19india/api#110]
I am super confused about what to expect from https://api.covid19india.org/states_daily.json . Is it supposed to have the data for the current date ? Earlier today ( 13th Apr ), this file contained the data for 13th. Now it is not here ... Can someone please clarify the expected behavior ?

**Comment by sudevschiz** [comment]
Sorry about this. Ideally, the data for the day should show up in the API between 23:30 to 00:30 hours IST.

Due to some timezone confusion in a scheduled trigger, the data for 13th April was present much before 12o clock.

Made a note of this. Above mentioned is the expected behaviour. However, I would suggest you to place extra checks on your end to handle such cases. Thank you
