### ISSUE TITLE
Data missing in the deaths and recoveries api

### ISSUE THREAD

**Issue by Aniruddha-S-Prasad** [covid19india/api#123]
In the data received from the deaths and recoveries API, there does not seem to be any data prior to the date 29/03/2020. This data, however, seems to be present in the raw_data, which is mentioned to be depreciated. Is there any chance to get the full data in a single place?

**Comment by sudevschiz** [comment]
We shifted to the Death and Recovery sheet on 29th March because we simply couldn't match recovery or death of a patient to an exact patient number. Will keep in mind about back-updating the death and recovery sheet. But it's hard work. Thanks for reporting. Keeping it open.

**Comment by onclave** [comment]
We are maintaining a timeseries dataset of statewise recoveries and death since `30/01/2020`. We are taking most of the data from here but have manually updated information prior `29/03/2020` by compiling multiple other data sources and news articles. You can check it [here](https://github.com/kalyaniuniversity/COVID-19-Datasets) if you need that data, though we are not keeping district-wise data. Hope this helps!
