### ISSUE TITLE
Varying Json response of the APIs

### ISSUE THREAD

**Issue by jyoti291** [covid19india/api#190]
**API**

- https://api.covid19india.org/raw_data.json
- https://api.covid19india.org/raw_data1.json
- https://api.covid19india.org/raw_data2.json 
- https://api.covid19india.org/raw_data3.json

**Issue**

Many applications are using the raw data API to build COVID-19  statistical dashboards and content.The **https://api.covid19india.org/raw_data.json** (till 26 April) provides unique patient number in **patientnumber** key.While the Live API does not provide any unique patient number to identity and compare it to prior records.(Only provides the entry ID).

**Solution**

- Please maintain a consistent response of the API.
- Please provide a unique identifier for the patients.

**Comment by sudevschiz** [comment]
The data curation process is changing rapidly to adapt to new scenarios. Hence the change in structure in raw_data3. We suggest using the aggregate APIs provided for any live application. That will have more stability because our website itself is using those endpoints. 

>Please maintain a consistent response of the API.
We will try to wrangle all the files together and provide it in the format of raw_data3 soon. However, there would be mismatches, as states move around the patient numbers. History may not reflect the current situation.

>Please provide a unique identifier for the patients.
We used to do this, however, we have now shifted to aggregate entry for states which are just reporting districtwise numbers (or sometime, just a single number for the state).

If you have further questions regarding raw_data, please do follow the discussion here :https://github.com/covid19india/api/issues/195 
Thank you!
