### ISSUE TITLE
api inconsistency in `statename` in national data and resources data

### ISSUE THREAD

**Issue by gurrrung** [covid19india/api#197]
In https://api.covid19india.org/data.json, states with `and` in their name are written like `Jammu and Kashmir`, `Andaman and Nicobar Islands`.
Whereas in https://api.covid19india.org/resources/resources.json, states with `and` in their name are written like `Jammu & Kashmir`, `Andaman & Nicobar Islands`. 

> I think same pattern should be followed for consistency.

**Comment by ff171217** [comment]
The total number of cases for west bengal has been updated today as 922 but the increase in the number of total cases from yesterday which is 127 has not been added to the national total. Also the number of discharged in the state has not been added to the national total. Requesting you to update the national total

**Comment by gurrrung** [comment]
> The total number of cases for west bengal has been updated today as 922 but the increase in the number of total cases from yesterday which is 127 has not been added to the national total. Also the number of discharged in the state has not been added to the national total. Requesting you to update the national total

This can be a new issue.

**Comment by alphasingh** [comment]
A similar issue was mentioned already before as well. 
#29 Sheet maintenance issue
How can this be avoided in future? @JunaidBabu

**Comment by sudevschiz** [comment]
We did a district name correction task in the past two days. Hence the mismatch. I will pass on the new spellings to the Essentials team to map too.

@alphasingh saw your other issues regarding S.A.S Nagar being expanded etc. Is that a compulsory edit. It takes a lot of work to fix the district names across multiple places. If it's not critical, I would like to leave this alternate spelling as is.

**Comment by alphasingh** [comment]
@sudevschiz the data being reflected on the maps should have the same "key" name, only then will it reflect its data. So, yes the fix is critical in the sense that even after having all the data in the API, we're not showing it on the web due to this.

**Suggestion**: 
Both web and API key names for each district/state should exist in a single place, like a common enum that is being used by both, to avoid any mismatch and unnecessary manual fixes.

**Comment by bee-rickey** [comment]
@alphasingh I think @sudevschiz's question about compulsory edit was for SAS Nagar. We will make sure they are consistent across the website and the data sheet and essentials. But should SAS Nagar be expanded is the question.

**Comment by sudevschiz** [comment]
I have passed on the new district list to the essentials team. It will get edited everywhere soon.

**Comment by alphasingh** [comment]
@bee-rickey As long as every state and district is being maintained with the same "key" name everywhere, I don't think we need to put an extra effort for SAS nagar alone. 
Let's keep it **as it is** everywhere, as of now, because I can see it with "key" name as ```S.A.S. Nagar``` on https://www.covid19india.org/state/PB and it reflects the same data as it should, i.e. from the API where it has the exact same "key" name as ```S.A.S. Nagar```

**Comment by bee-rickey** [comment]
> @bee-rickey As long as every state and district is being maintained with the same "key" name everywhere, I don't think we need to put an extra effort for SAS nagar alone.
> Let's keep it **as it is** everywhere, as of now, because I can see it with "key" name as `S.A.S. Nagar` on https://www.covid19india.org/state/PB and it reflects the same data as it should, i.e. from the API where it has the exact same "key" name as `S.A.S. Nagar`

Got it. Thanks!

**Comment by sudevschiz** [comment]
Resources data has now been deprecated. Closing this issue as it is irrelavant.
