### ISSUE TITLE
API for daily changes in zones per district

### ISSUE THREAD

**Issue by FrenziedWarrior** [covid19india/api#270]
Looking for a change in zones per district data for company project. Data is getting updated everyday. Any way to see historical changes in zones?

**Comment by sudevschiz** [comment]
We are not maintaining the historical zone information of districts in our Google Sheet, so it's not possible to provide information that way.

If it's crucial for your work, you should be able to loop through the previous commits of zone.json in the gh-pages and see how the changes happened. Word of advise : Zone data is not updated by governments religiously, so it's not really a great source of info.

Since we are not planning to provide this endpoint, closing this issue.

**Comment by FrenziedWarrior** [comment]
Thank you so much. I was able to grab the required from the gh-pages branch. And you're right about the zone data. It has become extremely hard to track these. If I had more time, I would sit and compile a state-wise database, but it changes really quick.
