### ISSUE TITLE
Negative numbers for daily active cases, daily # tests etc

### ISSUE THREAD

**Issue by ankitbar** [covid19india/api#273]
West Bengal data:
![image](https://user-images.githubusercontent.com/10872542/82535316-5434c200-9b64-11ea-8263-a75257e4d0e2.png)
Some more aggregates for other states:
![image](https://user-images.githubusercontent.com/10872542/82535578-ac6bc400-9b64-11ea-9fac-05d81e81deaa.png)

**Comment by sudevschiz** [comment]
When number of recoveries are more than confirmed cases, that means the cases reduced for that day. So daily change in active is negative. 

Daily test data is negative because states reported a lower value for total tests compared to yesterday reported in bulletin. This is an error from the state reporting side. We are reflecting the information they provided.

**Comment by iamnishanth** [comment]
dailyActive = dailyConfirmed - dailyRecovery - dailyDeaths.
So when dailyRecovery or dailyDeaths is greater than dailyConfirmed thats why the negative value.
