### ISSUE TITLE
Per date count is not been updated

### ISSUE THREAD

**Issue by john2014** [covid19india/api#376]
In https://api.covid19india.org/v3/data-all.json it has data for date June 28.

However if you goto per date url, https://api.covid19india.org/v3/data-2020-06-28.json, it gives a 404 error.

It seems both sources are not been updated at the same time. You can also later verify this issue on next day (June 29) data.

**Comment by shuklaayush** [comment]
This might have been a temporary issue related to GitHub serving. Whatever's there in data-all is split and dumped for each date at the time

**Comment by john2014** [comment]
Same issue is happening every day. The June 30 data already appears in /v3/data-all.json. 

However /v3/data-2020-06-30.json still gives a 404 error. It seems this file takes around 5-6 hours to update.

Could you please look into why there is a huge delay in updating daily data json file?

Currently the only option to get daily data is is to download the entire /v3/data-all.json file which is huge (around 12 MB).

**Comment by shuklaayush** [comment]
Looking at https://github.com/covid19india/api/commit/cee12112a6a28c734f3627492eb7cfd815e94fca, seems like a new date entry in `v3/data-all.json` and a new date file `v3/data-2020-06-30.json` are created at the same time. I'm not really sure what else to look at.

Just to be clear, the data for the last day available is stored in `v3/data.json`, while the data for previous days is kept as `v3/data-YYYY-MM-DD.json`. `data-all.json` is a combination of both which contains all date entries. Assuming your use case is only to get the latest numbers, then you should only be pulling `v3/data.json` and not any date-specific ones. The reason why `v3/data.json` (the one with the latest numbers) doesn't have a date is so that people don't have to worry about timezones when pulling.
