### ISSUE TITLE
Population data incorrect

### ISSUE THREAD

**Issue by john2014** [covid19india/api#388]
The population of many region in file https://api.covid19india.org/misc.json is incorrect.

Example: It says mumbai has a population of only 3.14 million. But it is around 18.41 million. What is the source of data?

**Comment by shuklaayush** [comment]
At least for Mumbai, it's not exactly incorrect. The population of Mumbai **district** is ~3 million. The issue is that the numbers reported by the Maharashtra State Government probably include the whole Mumbai Metropolitan area, and not just the Mumbai district. Will take a call on how to fix these inconsistencies.

Also, substantiate your claim by more than one example when you say that the population of **many** regions is incorrect.

Anyways, the source is [this](https://en.m.wikipedia.org/wiki/List_of_districts_in_India).

**Comment by john2014** [comment]
Here are the regions where differences of more than 90,000. I have compared the value in misc.json file with values from google search and some more authoritative websites (including wikipedia). 

Country_State_District: Value in misc.json -- value per google search -- difference
----------------------------------------------------------------------------------------------
India_Chandigarh: 1,179,000 -- 1,158,473 -- 20,527
India_Delhi: 19,814,000 -- 18,710,922 -- 1,103,078
India_Gujarat: 67,936,000 -- 63,872,399 -- 4,063,601
India_Haryana: 28,672,000 -- 28,204,692 -- 467,308
India_Puducherry: 1,504,000 -- 1,413,542 -- 90,458
India_Haryana_Hisar: 1,742,815 -- 544,829 -- 1,197,986
India_Puducherry_Puducherry: 950,289 -- 227,411 -- 722,878
India_TamilNadu_Tiruppur: 2,471,222 -- 650,000 -- 1,821,222
India_Telangana_Mahabubabad: 1,318,110 -- 770,170 -- 547,940
India_DadraAndNagarHaveliAndDamanAndDiu: 959,000 -- 615,724 -- 343,276

India_AndhraPradesh: 53,903,393 -- 52,221,000 -- 1,682,393
India_Assam: 35,607,039 -- 34,293,000 -- 1,314,039
India_Bihar: 124,799,926 -- 119,520,000 -- 5,279,926
India_Chhattisgarh: 29,436,231 -- 28,724,000 -- 712,231
India_HimachalPradesh: 7,451,955 -- 7,300,000 -- 151,955
India_JammuAndKashmir: 13,606,320 -- 13,203,000 -- 403,320
India_Jharkhand: 38,593,948 -- 37,403,000 -- 1,190,948
India_Karnataka: 67,562,686 -- 65,798,000 -- 1,764,686
India_Kerala: 35,699,443 -- 35,125,000 -- 574,443
India_MadhyaPradesh: 85,358,965 -- 82,232,000 -- 3,126,965
India_Maharashtra: 123,144,223 -- 122,153,000 -- 991,223
India_Meghalaya: 3,366,710 -- 3,224,000 -- 142,710
India_Odisha: 46,356,334 -- 43,671,000 -- 2,685,334
India_Punjab: 30,141,373 -- 29,859,000 -- 282,373
India_Rajasthan: 81,032,689 -- 77,264,000 -- 3,768,689
India_TamilNadu: 77,841,267 -- 75,695,000 -- 2,146,267
India_Tripura: 4,169,794 -- 3,992,000 -- 177,794
India_Uttarakhand: 11,250,858 -- 11,141,000 -- 109,858
India_UttarPradesh: 237,882,725 -- 224,979,000 -- 12,903,725
India_WestBengal: 99,609,303 -- 96,906,000 -- 2,703,303
India_Telangana: 39,362,732 -- 37,220,000 -- 2,142,732
India_Nagaland: 2,249,695 -- 2,150,000 -- 99,695
India_Maharashtra_Mumbai: 18,978,000 -- 3,145,966 -- 15,832,034

**Comment by shuklaayush** [comment]
For the states, population projection from [this](https://nhm.gov.in/New_Updates_2018/Report_Population_Projection_2019.pdf) GoI report has been used since 2011 Census numbers are a bit outdated. Since there's no analogous report for districts, Census 2011 figures have been used (taken from Wikipedia). As for the rest of the mismatches, I think you're mixing up populations of districts and cities having the same name.
