### ISSUE TITLE
[Broken CSV] District Time-series

### ISSUE THREAD

**Issue by parshnt** [covid19india/api#393]
Hi @JunaidBabu 

with the latest commit, you seemed to have removed the daily CSV files for the Districts.
I have a project that used those CSV files for district-wise data time-series. Can you point to any alternative?

Thanks

**Comment by JunaidBabu** [comment]
Hi @parshnt 

Sorry about this. The district daily csv we had so far was created by taking snapshots at midnight for each day. This method was wrong because when we had made any change in a previous date that would not be reflected in the csv files. 

You can use the [v3](https://github.com/covid19india/api/tree/gh-pages/v3) or [v4](https://github.com/covid19india/api/tree/gh-pages/v4) version of the api for getting District time-series. This is updated even when there is a backdated change in Sheets.

**Comment by parshnt** [comment]
Sure, I'll look into it.
But we won't be seeing any CSV version of the same?

**Comment by shuklaayush** [comment]
@parshnt I added [this](https://github.com/covid19india/api/blob/gh-pages/csv/latest/districts.csv) just now. See if it's useful

**Comment by vasthav2k** [comment]
district wise json isn't updated yet

**Comment by parshnt** [comment]
@shuklaayush 
Thanks a lot, I was exactly looking for this.

**Comment by JunaidBabu** [comment]
Hi @vasthav2k 

district_daily.json was generated using the daily snapshots of districts csv files. Since we removed them because they had inaccuracies, it's not possible to update districts_daily.json anymore.

Could you please use the v3 or v4 versions for json or the csv mentioned in the above comments?

**Comment by vasthav2k** [comment]
@JunaidBabu 

Yes, thanks a lot.
I can work with CSV file.

**Comment by VinitSawant09** [comment]
I had raised an issue earlier regarding the districts_daily.json file missing. As per the above comments in the v4 version I was able to find data on individual states like for example : timeseries-MH.json. I am trying to access the json through AJAX call but its throwing CORS error.
