### ISSUE TITLE
Telangana District Wise Data Missing

### ISSUE THREAD

**Issue by vasthav2k** [covid19india/api#398]
Hi @JunaidBabu , @shuklaayush 
In the latest updates [districts.csv](https://github.com/covid19india/api/blob/gh-pages/csv/latest/districts.csv) Some of the states data is missing(Telangana Data)
Please look into the issue

**Comment by JunaidBabu** [comment]
This is because Telangana is not providing any district-wise data.

**Comment by vasthav2k** [comment]
Hi @JunaidBabu 
Yes,you are correct they are not providing exact recoveries and deaths for every district.

But isn't it possible to just update
Confirmed cases as done earlier until now..?

Thanks in Advance

**Comment by KrishnaTejaJ** [comment]
Although, the entire data is not available, status of new positive cases is being tweeted by [Eatala Rajender](https://twitter.com/Eatala_Rajender). Can you please make efforts in updating this data. Thank you!

**Comment by sudevschiz** [comment]
We used to maintain the district information for Telengana just because daily new cases are being reported in the bulletin as @KrishnaTejaJ  mentioned. But for a long time, there has not been a full update on how many cumulative cases, recoveries and deaths are there in each of these districts. We cannot continue speculating the total numbers without this anchor. Several analysts posted incorrect insights because of this outdated data being present in our APIs. That's undesirable.

We will bring this back districtwise details if the state publishes the total number of cases and recoveries and deaths at least once in future. 

That being said, we do capture the daily district confirmed counts in raw data. They're just cleaned out in the aggregate APIs. If you need it specifically, you can always parse through the raw data to get this information.

**Comment by bee-rickey** [comment]
@vasthav2k @KrishnaTejaJ The biggest problem is what Dave said about not having enough clarity for data. Even with the district data given per day, there's enough older data without district information. Having data only for confirmed but not for others makes it difficult to maintain. As of now we have taken a call on not showing any district details for certain states that are not providing enough district details.

**Comment by MillikenDB1** [comment]
Try looking for district Hyderabad. It use to work. Now it does not

**Comment by MillikenDB1** [comment]
Name changed in data on 12 June

**Comment by bee-rickey** [comment]
@MillikenDB1 A purposeful change. We've stopped aggregating data for Telangana since the govt does not provide enough district details. The raw_data files still have the details though.
