### ISSUE TITLE
[FR] Consider adding an endpoint that directs to the latest patient-level JSON file

### ISSUE THREAD

**Issue by axmb** [covid19india/api#418]
I'm working on [a project](https://github.com/globaldothealth/list) that aggregates global patient-level COVID data. Your API is really fantastic -- certainly one of the best organized and documented out there.

It'd be even more useful to us if there were an endpoint at which the latest patient-level data were available. For instance, on August 22nd, this endpoint would automatically have changed from redirecting to the 13th raw file to the 14th raw file.

Is this feasible as a feature, and would you want/need help doing this?

**Comment by bee-rickey** [comment]
We have the v4 endpoint which has all the data already available (aggregated per day though). So is there a real requirement for this at all? The way I see it, it's much easier to use the aggregated end points since most of the data being given out by the govt is aggregated. Individual raw files do not necessarily have better information than aggregated API endpoints.

**Comment by axmb** [comment]
We're assembling data in part for epidemiological research, and having the per-patient ("line list") level data is critical. Otherwise, as you said, the aggregate end points would work.

With that context, WDYT about the feasibility of this?

**Comment by bee-rickey** [comment]
@axmb Sorry I had missed this response. As I said, there's little to zero per-patient data being released by the Indian government. So adding an additional logic to get the latest file makes no major value add. Most of what is released now is district level aggregated data.
