### ISSUE TITLE
Consider licensing by CC-BY (removing the ShareAlike SA clause)

### ISSUE THREAD

**Issue by themonk911** [covid19india/api#427]
Thanks for the repo, we've been using your data source in our project https://github.com/GoogleCloudPlatform/covid-19-open-data. Unfortunately we've been requested to remove all data sources that have SA as part of the clause, since it is a viral clause like GPL. CC-BY (without the SA clause) would be much closer to the MIT license that you use for your code. 

We would really like to continue using your incredible data for our project, and if you could consider removing the SA clause (switching to a CC-BY) license, we can do so. Thanks!

**Comment by bee-rickey** [comment]
@themonk911 Hi there. We are having an internal discussion about this. Meanwhile, I wanted to know if you too would be dropping the SA clause from your project? The reason why we've kept it as CC-BY-SA is to avoid profiteering from the data. Having an SA clause forces the downstream to remain open.

**Comment by owahltinez** [comment]
Hi @bee-rickey I'm working with @themonk911 on the project linked above.

We will be moving from CC BY CA to CC BY as soon as this issue is resolved. Because our output will be CC BY, that means we can no longer use any data source licensed as CC BY SA (or a similarly restrictive license).

Our reasoning for the license change is motivated by wanting to make the data useful to more people with less restrictions on how they can build upon it.

**Comment by bee-rickey** [comment]
@owahltinez @themonk911 We've updated the licensing for data to CC-BY-4.0.

**Comment by themonk911** [comment]
Thank you so much, this is very much appreciated :)
