### ISSUE TITLE
District data is too large to import into Google Sheets

### ISSUE THREAD

**Issue by a-baheti** [covid19india/api#462]
Using the function _=IMPORTDATA("https://api.covid19india.org/csv/latest/districts.csv")_ gives the following error: **_Resource at URL contents exceeded maximum size_**, because the data has too many rows.

Can this data be put in a wide format, similar to State Wise Daily (_https://api.covid19india.org/csv/latest/state_wise_daily.csv_) data? If every district were a column, it would be possible to import the live data into Google Sheets.

**Comment by sudevschiz** [comment]
Hi,
Wide format was found to be impractical as the are 700+ districts. Since the format has been established, it would be problematic to change it now as it might break some other applications. 

There are custom Google Scripts available to import large data to Google Sheets. Otherwise, consider downloading the csv and imorting it.

Thank you.
